export const MODULE_NAME = 'memnext';
export const MODULE_NAME_FANCY = 'MemNext';
export const PROGRESS_BAR_ID = `${MODULE_NAME}_progress_bar`;

// CSS Classes & Selectors
export const css_message_div = `${MODULE_NAME}_display`;
export const css_short_memory = `${MODULE_NAME}_short_memory`;
export const css_long_memory = `${MODULE_NAME}_long_memory`;
export const css_exclude_memory = `${MODULE_NAME}_exclude_memory`;
export const css_lagging_memory = `${MODULE_NAME}_lagging_memory`;
export const css_removed_message = `${MODULE_NAME}_removed_message`;
export const summary_div_class = `${MODULE_NAME}_text`;
export const summary_reasoning_class = `${MODULE_NAME}_reasoning`;
export const css_button_separator = `${MODULE_NAME}_button_separator`;
export const css_edit_textarea = `${MODULE_NAME}_edit_textarea`;
export const settings_div_id = `${MODULE_NAME}_settings`;
export const settings_content_class = `${MODULE_NAME}_settings_content`;
export const group_member_enable_button = `${MODULE_NAME}_group_member_enable`;
export const group_member_enable_button_highlight = `${MODULE_NAME}_group_member_enabled`;

// In-chat Message Buttons
export const summarize_button_class = `${MODULE_NAME}_summarize_button`;
export const edit_button_class = `${MODULE_NAME}_edit_button`;
export const forget_button_class = `${MODULE_NAME}_forget_button`;

// Macros for memory injection
export const long_memory_macro = `memnext-long-term-memory`;
export const short_memory_macro = `memnext-short-term-memory`;
export const generic_memories_macro = `memnext-memories`;

// Interceptor symbol
export const IGNORE_SYMBOL = Symbol('memnext_ignore');

// Default Prompt Templates
export const default_message_summary_prompt = `You are a summarization assistant. Summarize the given fictional narrative in a single, concise statement of fact.
Responses should be no more than {{words}} words.
Include names when possible.
Response must be in the past tense.
Your response must ONLY contain the summary.

{{#if history}}
Following is a history of messages for context:
{{history}}
{{/if}}

Following is the message generated by {{speaker}} to summarize:
{{message}}
`;

export const default_short_to_long_prompt = `You are a memory consolidation assistant. Incorporate the recent events into the established long-term memory narrative.
Maintain chronological progression and integrate new developments seamlessly.
Keep the narrative coherent, structured, and factual.
Your response must ONLY contain the updated consolidated memory.

[Existing Long-Term Memory]:
{{existing_long_memory}}

[Recent Events to Incorporate]:
{{new_events}}
`;

export const default_long_compaction_prompt = `You are a memory consolidation assistant. The existing long-term memory narrative has grown too long for the context budget.
Condense and compress the following narrative while strictly preserving essential plot points, character relations, major events, and crucial decisions.
Remove minor transitional details and summarize older events more aggressively.
Your response must ONLY contain the condensed narrative.

[Long-Term Memory to Condense]:
{{long_memory}}
`;

export const default_long_template = `[Past Events Summary]:\n{{${generic_memories_macro}}}\n`;
export const default_short_template = `[Recent Events Summary]:\n{{${generic_memories_macro}}}\n`;

export const default_macro_settings = {
  name: "New Macro",
  default: false,
  enabled: true,
  type: "preset",
  instruct_template: false,
  apply_regex: false,
  start: 1,
  end: 5,
  bot_messages: true,
  user_messages: true,
  bot_summaries: false,
  user_summaries: false,
  command: "",
  regex_scripts: [],
  description: ""
};

export const default_summary_macros = {
  "message": {
    name: "message",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The message being summarized"
  },
  "speaker": {
    name: "speaker",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The name of the character or user who sent the message"
  },
  "words": {
    name: "words",
    default: true,
    enabled: true,
    type: "custom",
    instruct_template: false,
    apply_regex: false,
    command: "/memnext-max-summary-tokens",
    description: "Max response tokens defined by preset"
  },
  "history": {
    name: "history",
    default: true,
    enabled: false,
    type: "preset",
    instruct_template: true,
    apply_regex: true,
    start: 1,
    end: 6,
    bot_messages: true,
    user_messages: true,
    bot_summaries: false,
    user_summaries: false
  },
  "crop_history": {
    name: "crop_history",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: false,
    description: "Extract N previous messages (e.g. {{crop_history 5}})"
  }
};
