export const MODULE_NAME = 'memnext';
export const MODULE_NAME_FANCY = 'MemNext';
export const PROGRESS_BAR_ID = `${MODULE_NAME}_progress_bar`;

// CSS Classes & Selectors
export const css_message_div = `${MODULE_NAME}_display`;
export const css_short_memory = `${MODULE_NAME}_short_memory`;
export const css_long_memory = `${MODULE_NAME}_long_memory`;
export const css_exclude_memory = `${MODULE_NAME}_exclude_memory`;
export const css_lagging_memory = `${MODULE_NAME}_lagging_memory`;
export const css_removed_message = `${MODULE_NAME}_removed_message`;
export const summary_div_class = `${MODULE_NAME}_text`;
export const summary_reasoning_class = `${MODULE_NAME}_reasoning`;
export const css_button_separator = `${MODULE_NAME}_button_separator`;
export const css_edit_textarea = `${MODULE_NAME}_edit_textarea`;
export const settings_div_id = `${MODULE_NAME}_settings`;
export const settings_content_class = `${MODULE_NAME}_settings_content`;
export const group_member_enable_button = `${MODULE_NAME}_group_member_enable`;
export const group_member_enable_button_highlight = `${MODULE_NAME}_group_member_enabled`;

// In-chat Message Buttons
export const summarize_button_class = `${MODULE_NAME}_summarize_button`;
export const edit_button_class = `${MODULE_NAME}_edit_button`;
export const forget_button_class = `${MODULE_NAME}_forget_button`;

// Macros for memory injection
export const long_memory_macro = `memnext_long`;
export const short_memory_macro = `memnext_short`;
export const generic_memories_macro = `memories`;

// Interceptor symbol
export const IGNORE_SYMBOL = Symbol('memnext_ignore');

// Default Prompt Templates
export const default_message_summary_prompt = `You are a summarization assistant. Summarize the given fictional narrative in a single, concise statement of fact.
Responses should be no more than {{words}} words.
Include names when possible.
Response must be in the past tense.
Your response must ONLY contain the summary.

{{#if history}}
Following is a history of messages for context:
{{history}}
{{/if}}

Following is the message generated by {{speaker}} to summarize:
{{message}}
`;

export const default_short_to_long_prompt = `You are an expert lore archivist. Your task is to compress a chronological list of recent short-term events into a dense, cohesive narrative state.

### INSTRUCTIONS:
1. RUTHLESS FILTERING: Completely erase minor character interactions, flirting, body language (e.g., tail wagging, kissing), and step-by-step mundane actions (e.g., eating specific food pieces).
2. PRESERVE CORE PLOT: Keep ONLY combat outcomes, injuries, healing, location changes, significant lore reveals, and critical items.
3. ADVANCED SYNTAX: Maximize information density. Combine related events into complex sentences using participles and relative clauses. Do NOT use repetitive "Subject-Verb" structures (e.g., avoid "Man did X. Woman did Y.").
4. TONE: Dry, factual, and strictly chronological.

### RECENT EVENTS:
{{short_memory_list}}

### COMPRESSED STORY STATE (Max {{long_history_size}} words):
`;

export const default_short_recompaction_prompt = default_short_to_long_prompt;

export const default_long_compaction_prompt = `You are an expert lore archivist maintaining a dynamic, long-term story encyclopedia.
Your task is to merge the NEW STORY CHAPTER into the PREVIOUS STORY STATE, creating a single, updated, and highly compressed chronological narrative.

### INSTRUCTIONS:
1. SEAMLESS MERGE: Integrate the new events chronologically at the end of the previous state.
2. STATE OVERWRITE (CRITICAL): Update outdated facts immediately. If characters change location, achieve a previous goal, or change their status in the new chapter, replace the old information with the new reality.
3. EXTREME COMPRESSION: Condense older events from the PREVIOUS STORY STATE into brief background context to save space. Older events require less detail than recent ones.
4. ADVANCED SYNTAX: Use dense, complex sentences with participles and relative clauses. Maintain a strictly factual, encyclopedia-like tone.

### PREVIOUS STORY STATE:
{{long_memory}}

### NEW STORY CHAPTER:
{{new_history_chunk}}

### UPDATED STORY STATE (Max {{long_term_memory_size}} words):
`;

export const default_long_template = `[Past Events Summary]:\n{{${long_memory_macro}}}\n`;
export const default_short_template = `[Recent Events Summary]:\n{{${short_memory_macro}}}\n`;

export const default_macro_settings = {
  name: "New Macro",
  default: false,
  enabled: true,
  type: "preset",
  instruct_template: false,
  apply_regex: false,
  start: 1,
  end: 5,
  bot_messages: true,
  user_messages: true,
  bot_summaries: false,
  user_summaries: false,
  command: "",
  regex_scripts: [],
  description: ""
};

export const default_summary_macros = {
  "message": {
    name: "message",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The message being summarized"
  },
  "speaker": {
    name: "speaker",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The name of the character or user who sent the message"
  },
  "words": {
    name: "words",
    default: true,
    enabled: true,
    type: "custom",
    instruct_template: false,
    apply_regex: false,
    command: "/memnext-max-summary-tokens",
    description: "Max response tokens defined by preset"
  },
  "history": {
    name: "history",
    default: true,
    enabled: false,
    type: "preset",
    instruct_template: true,
    apply_regex: true,
    start: 1,
    end: 6,
    bot_messages: true,
    user_messages: true,
    bot_summaries: false,
    user_summaries: false
  },
  "crop_history": {
    name: "crop_history",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: false,
    description: "Extract N previous messages (e.g. {{crop_history 5}})"
  }
};
