/* eslint-disable */
import { getRegexScripts, runRegexScript } from '../../../../scripts/extensions/regex/engine.js';
import { getStringHash, debounce, copyText, trimToEndSentence, download, parseJsonFile, stringToRange, waitUntilCondition } from '../../../utils.js';
import { animation_duration, scrollChatToBottom, saveSettingsDebounced, getCharacterCardFields, messageFormatting, generateRaw, createRawPrompt, getMaxContextSize, streamingProcessor, amount_gen, system_message_types, extension_prompt_roles, extension_prompt_types, CONNECT_API_MAP, main_api, online_status, chat_metadata } from '../../../../script.js';
import { getContext, extension_settings, saveMetadataDebounced } from '../../../extensions.js';
import { formatInstructModePrompt } from '../../../instruct-mode.js';
import { selected_group, openGroupId } from '../../../group-chats.js';
import { loadMovingUIState, power_user } from '../../../power-user.js';
import { dragElement } from '../../../RossAscends-mods.js';
import { debounce_timeout } from '../../../constants.js';
import { MacrosParser } from '../../../macros.js';
import { itemizedPrompts } from '../../../../scripts/itemized-prompts.js';
import { t, translate } from '../../../i18n.js';
export
// Macros for memory injection
const long_memory_macro = `memnext-long-term-memory`;
export const short_memory_macro = `memnext-short-term-memory`;
export const generic_memories_macro = `memnext-memories`;

// Message button classes
export
// Default prompt templates
const default_message_summary_prompt = `You are a summarization assistant. Summarize the given fictional narrative in a single, concise statement of fact.
Responses should be no more than {{words}} words.
Include names when possible.
Response must be in the past tense.
Your response must ONLY contain the summary.

{{#if history}}
Following is a history of messages for context:
{{history}}
{{/if}}

Following is the message generated by {{speaker}} to summarize:
{{message}}
`;
export const default_short_to_long_prompt = `You are a memory consolidation assistant. Incorporate the recent events into the established long-term memory narrative.
Maintain chronological progression and integrate new developments seamlessly.
Keep the narrative coherent, structured, and factual.
Your response must ONLY contain the updated consolidated memory.

[Existing Long-Term Memory]:
{{existing_long_memory}}

[Recent Events to Incorporate]:
{{new_events}}
`;
export const default_long_compaction_prompt = `You are a memory consolidation assistant. The existing long-term memory narrative has grown too long for the context budget.
Condense and compress the following narrative while strictly preserving essential plot points, character relations, major events, and crucial decisions.
Remove minor transitional details and summarize older events more aggressively.
Your response must ONLY contain the condensed narrative.

[Long-Term Memory to Condense]:
{{long_memory}}
`;
export const default_long_template = `[Past Events Summary]:\n{{${generic_memories_macro}}}\n`;
export const default_short_template = `[Recent Events Summary]:\n{{${generic_memories_macro}}}\n`;
export const default_summary_macros = {
  "message": {
    name: "message",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The message being summarized"
  },
  "speaker": {
    name: "speaker",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: true,
    description: "The name of the character or user who sent the message"
  },
  "words": {
    name: "words",
    default: true,
    enabled: true,
    type: "custom",
    instruct_template: false,
    apply_regex: false,
    command: "/memnext-max-summary-tokens",
    description: "Max response tokens defined by preset"
  },
  "history": {
    name: "history",
    default: true,
    enabled: false,
    type: "preset",
    instruct_template: true,
    apply_regex: true,
    start: 1,
    end: 6,
    bot_messages: true,
    user_messages: true,
    bot_summaries: false,
    user_summaries: false
  },
  "crop_history": {
    name: "crop_history",
    default: true,
    enabled: true,
    type: "special",
    instruct_template: false,
    apply_regex: false,
    description: "Extract N previous messages (e.g. {{crop_history 5}})"
  }
};
export function get_message_prompts(index) {
  for (let i = 0; i < itemizedPrompts.length; i++) {
    let itemized_prompt = itemizedPrompts[i];
    if (itemized_prompt.mesId === index) {
      return itemized_prompt;
    }
  }
}